# Generated by Django 5.1.5 on 2025-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('csv_file', models.FileField(upload_to='csv_uploads/')),
                ('description', models.TextField(blank=True, null=True)),
                ('class_time', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('teacher', 'Teacher'), ('online', 'Online'), ('student', 'Student'), ('cheating', 'Cheating'), ('hybrid', 'Hybrid')], default='student', max_length=50)),
            ],
        ),
    ]
